services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./victim-web
    ports:
      - "8080:3000"
    environment:
      DATABASE_URL: postgres://user:1234@db:5432/database
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network
      - frontend-network
    volumes:
      - ./victim-web:/app # เชื่อมโฟลเดอร์เครื่องเรา เข้าไปทับใน Container
      - /app/node_modules # ยกเว้นโฟลเดอร์นี้ (ให้ใช้ของใน Docker ห้ามเอาของเครื่องเราไปทับ)
      - /app/.next # ยกเว้น cache ของ next build

  attacker-basic:
    build: ./attacker-bot
    environment:
      TARGET_ENDPOINT: basic # โจมตี endpoint ที่ไม่มี Rate Limit
      PYTHONUNBUFFERED: 1
    networks:
      - frontend-network
    volumes:
      - ./attacker-bot:/app # เชื่อมโฟลเดอร์เครื่องเรา เข้าไปทับใน Container
      - /app/__pycache__ # ยกเว้นโฟลเดอร์นี้
    deploy:
      replicas: 10 # 5 Bot โจมตี basic

  attacker-ratelimit:
    build: ./attacker-bot
    environment:
      TARGET_ENDPOINT: rate-limit # โจมตี endpoint ที่มี Rate Limit
      PYTHONUNBUFFERED: 1
    networks:
      - frontend-network
    volumes:
      - ./attacker-bot:/app
      - /app/__pycache__
    deploy:
      replicas: 10 # 5 Bot โจมตี rate-limit

networks:
  frontend-network: # วงนี้ใครก็เข้าได้ (Bot, Web)
  backend-network: # วงนี้ห้ามคนนอกเข้า (Web, DB)
    internal: true # ใส่ตรงนี้เพื่อบอก Docker ว่าห้ามออกเน็ต ห้ามใครเข้า (ปลอดภัยสูงสุด)

volumes:
  db_data:
